name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Display availiable destinations
        run: |
          xcodebuild -workspace It-works.xcodeproj/project.xcworkspace -scheme "It-works (iOS)" -showdestinations
      - name: Build
        run: |
          xcodebuild -workspace It-works.xcodeproj/project.xcworkspace -scheme "It-works (iOS)" -destination name="iphonesimulator12.4" -enableCodeCoverage YES test
      - name: Upload to Codecov with bash uploader
        run: |
          bash <(curl -s https://codecov.io/bash)
